export const categoryData = [
    { categoryID: "1", categoryName: "category1", imageURL: "", menuID: "1", order: "0", restaurantID: "1" },
    { categoryID: "2", categoryName: "category2", imageURL: "", menuID: "1", order: "1", restaurantID: "1" },
    { categoryID: "3", categoryName: "category3", imageURL: "", menuID: "1", order: "2", restaurantID: "1" },
    { categoryID: "4", categoryName: "category4", imageURL: "", menuID: "1", order: "3", restaurantID: "1" },
    { categoryID: "5", categoryName: "category5", imageURL: "", menuID: "1", order: "4", restaurantID: "1" },
    { categoryID: "6", categoryName: "category6", imageURL: "", menuID: "1", order: "5", restaurantID: "1" },
    { categoryID: "7", categoryName: "category7", imageURL: "", menuID: "1", order: "6", restaurantID: "1" },
    { categoryID: "8", categoryName: "category8", imageURL: "", menuID: "1", order: "7", restaurantID: "1" },
    { categoryID: "9", categoryName: "category9", imageURL: "", menuID: "1", order: "8", restaurantID: "1" },
    { categoryID: "10", categoryName: "category10", imageURL: "", menuID: "1", order: "9", restaurantID: "1" },
    { categoryID: "11", categoryName: "category11", imageURL: "", menuID: "2", order: "10", restaurantID: "1" },
    { categoryID: "12", categoryName: "category12", imageURL: "", menuID: "2", order: "11", restaurantID: "1" },
    { categoryID: "13", categoryName: "category13", imageURL: "", menuID: "2", order: "12", restaurantID: "1" },
    { categoryID: "14", categoryName: "category14", imageURL: "", menuID: "3", order: "13", restaurantID: "1" },
    { categoryID: "15", categoryName: "category15", imageURL: "", menuID: "3", order: "14", restaurantID: "1" },
    { categoryID: "16", categoryName: "category16", imageURL: "", menuID: "3", order: "15", restaurantID: "1" },
]