
import food1 from '../Assets/food1.png'
import food2 from '../Assets/food2.png'
import food3 from '../Assets/food3.png'
import food4 from '../Assets/food4.png'
import food5 from '../Assets/food5.png'
import food6 from '../Assets/food6.png'

export const foodData = [
    { foodID: "1", calories: "2", categoryID: "1", description: "Entree Ingredient Information", estimatedTime: "", images: [food1, "", ""], label: "", menuID: "1", name: "food1", order: "0", recommendedProducts: ["1", "3", "5"], restaurantID: "1", prices: "$13", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "2", calories: "2", categoryID: "1", description: "Entree Ingredient Information", estimatedTime: "", images: ["", "", ""], label: "", menuID: "1", name: "food2", order: "1", recommendedProducts: ["3", "2", "8"], restaurantID: "1", prices: "$14", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "3", calories: "2", categoryID: "1", description: "Entree Ingredient Information", estimatedTime: "", images: [food3, "", ""], label: "", menuID: "1", name: "food3", order: "2", recommendedProducts: ["7", "3", "1"], restaurantID: "1", prices: "$7", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "4", calories: "2", categoryID: "1", description: "Entree Ingredient Information", estimatedTime: "", images: ["", "", ""], label: "", menuID: "1", name: "food4", order: "3", recommendedProducts: ["2", "3", "8"], restaurantID: "1", prices: "$10", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "5", calories: "2", categoryID: "1", description: "Entree Ingredient Information", estimatedTime: "", images: [food5, "", ""], label: "", menuID: "1", name: "food5", order: "4", recommendedProducts: ["3", "5", "8"], restaurantID: "1", prices: "$17", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "6", calories: "2", categoryID: "2", description: "Entree Ingredient Information", estimatedTime: "", images: [food5, "", ""], label: "", menuID: "1", name: "food6", order: "0", recommendedProducts: ["7", "3", "4"], restaurantID: "1", prices: "$19", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "7", calories: "2", categoryID: "2", description: "Entree Ingredient Information", estimatedTime: "", images: [food4, "", ""], label: "", menuID: "1", name: "food7", order: "1", recommendedProducts: ["8", "4", "2"], restaurantID: "1", prices: "$20", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "8", calories: "2", categoryID: "2", description: "Entree Ingredient Information", estimatedTime: "", images: ["", "", ""], label: "", menuID: "1", name: "food8", order: "2", recommendedProducts: ["6", "3", "4"], restaurantID: "1", prices: "$24", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "9", calories: "2", categoryID: "2", description: "Entree Ingredient Information", estimatedTime: "", images: [food2, "", ""], label: "", menuID: "1", name: "food9", order: "3", recommendedProducts: ["4", "3", "3"], restaurantID: "1", prices: "$14", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "10", calories: "2", categoryID: "2", description: "Entree Ingredient Information", estimatedTime: "", images: ["", "", ""], label: "", menuID: "1", name: "food10", order: "4", recommendedProducts: ["6", "7", "3"], restaurantID: "1", prices: "$15", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "11", calories: "2", categoryID: "3", description: "Entree Ingredient Information", estimatedTime: "", images: [food4, "", ""], label: "", menuID: "1", name: "food11", order: "0", recommendedProducts: ["3", "6", "2"], restaurantID: "1", prices: "$17", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "12", calories: "2", categoryID: "3", description: "Entree Ingredient Information", estimatedTime: "", images: [food2, "", ""], label: "", menuID: "1", name: "food12", order: "1", recommendedProducts: ["5", "6", "3"], restaurantID: "1", prices: "$20", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "13", calories: "2", categoryID: "3", description: "Entree Ingredient Information", estimatedTime: "", images: [food3, "", ""], label: "", menuID: "1", name: "food13", order: "2", recommendedProducts: ["2", "6", "3"], restaurantID: "1", prices: "$22", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "14", calories: "2", categoryID: "3", description: "Entree Ingredient Information", estimatedTime: "", images: [food5, "", ""], label: "", menuID: "1", name: "food14", order: "3", recommendedProducts: ["6", "3", "6"], restaurantID: "1", prices: "$25", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "15", calories: "2", categoryID: "3", description: "Entree Ingredient Information", estimatedTime: "", images: [food1, "", ""], label: "", menuID: "1", name: "food15", order: "4", recommendedProducts: ["2", "3", "7"], restaurantID: "1", prices: "$26", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "16", calories: "2", categoryID: "4", description: "Entree Ingredient Information", estimatedTime: "", images: [food3, "", ""], label: "", menuID: "2", name: "food16", order: "0", recommendedProducts: ["4", "6", "3"], restaurantID: "1", prices: "$2", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "17", calories: "2", categoryID: "4", description: "Entree Ingredient Information", estimatedTime: "", images: [food2, "", ""], label: "", menuID: "2", name: "food17", order: "1", recommendedProducts: ["7", "3", "2"], restaurantID: "1", prices: "$27", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "18", calories: "2", categoryID: "4", description: "Entree Ingredient Information", estimatedTime: "", images: [food5, "", ""], label: "", menuID: "2", name: "food18", order: "2", recommendedProducts: ["5", "4", "3"], restaurantID: "1", prices: "$15", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "19", calories: "2", categoryID: "4", description: "Entree Ingredient Information", estimatedTime: "", images: [food3, "", ""], label: "", menuID: "2", name: "food19", order: "3", recommendedProducts: ["6", "3", "2"], restaurantID: "1", prices: "$7", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "20", calories: "2", categoryID: "4", description: "Entree Ingredient Information", estimatedTime: "", images: [food2, "", ""], label: "", menuID: "2", name: "food20", order: "4", recommendedProducts: ["8", "7", "2"], restaurantID: "1", prices: "$8", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "21", calories: "2", categoryID: "5", description: "Entree Ingredient Information", estimatedTime: "", images: [food5, "", ""], label: "", menuID: "2", name: "food21", order: "0", recommendedProducts: ["5", "4", "3"], restaurantID: "1", prices: "$12", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "22", calories: "2", categoryID: "5", description: "Entree Ingredient Information", estimatedTime: "", images: [food1, "", ""], label: "", menuID: "2", name: "food22", order: "1", recommendedProducts: ["9", "8", "2"], restaurantID: "1", prices: "$13", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "23", calories: "2", categoryID: "5", description: "Entree Ingredient Information", estimatedTime: "", images: [food3, "", ""], label: "", menuID: "2", name: "food23", order: "2", recommendedProducts: ["4", "3", "2"], restaurantID: "1", prices: "$13", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "24", calories: "2", categoryID: "5", description: "Entree Ingredient Information", estimatedTime: "", images: [food4, "", ""], label: "", menuID: "2", name: "food24", order: "3", recommendedProducts: ["5", "7", "4"], restaurantID: "1", prices: "$31", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "25", calories: "2", categoryID: "5", description: "Entree Ingredient Information", estimatedTime: "", images: [food2, "", ""], label: "", menuID: "2", name: "food25", order: "4", recommendedProducts: ["5", "4", "3"], restaurantID: "1", prices: "$21", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "26", calories: "2", categoryID: "6", description: "Entree Ingredient Information", estimatedTime: "", images: [food2, "", ""], label: "", menuID: "2", name: "food26", order: "0", recommendedProducts: ["5", "3", "4"], restaurantID: "1", prices: "$12", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "27", calories: "2", categoryID: "6", description: "Entree Ingredient Information", estimatedTime: "", images: [food5, "", ""], label: "", menuID: "2", name: "food27", order: "1", recommendedProducts: ["7", "4", "3"], restaurantID: "1", prices: "$23", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "28", calories: "2", categoryID: "6", description: "Entree Ingredient Information", estimatedTime: "", images: [food3, "", ""], label: "", menuID: "2", name: "food28", order: "2", recommendedProducts: ["5", "17", "3"], restaurantID: "1", prices: "$12", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "29", calories: "2", categoryID: "6", description: "Entree Ingredient Information", estimatedTime: "", images: [food4, "", ""], label: "", menuID: "2", name: "food29", order: "3", recommendedProducts: ["4", "6", "3"], restaurantID: "1", prices: "$25", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "30", calories: "2", categoryID: "6", description: "Entree Ingredient Information", estimatedTime: "", images: [food5, "", ""], label: "", menuID: "2", name: "food30", order: "4", recommendedProducts: ["7", "2", "3"], restaurantID: "1", prices: "$16", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "31", calories: "2", categoryID: "7", description: "Entree Ingredient Information", estimatedTime: "", images: [food1, "", ""], label: "", menuID: "3", name: "food31", order: "0", recommendedProducts: ["8", "6", "5"], restaurantID: "1", prices: "$18", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "32", calories: "2", categoryID: "7", description: "Entree Ingredient Information", estimatedTime: "", images: [food3, "", ""], label: "", menuID: "3", name: "food32", order: "1", recommendedProducts: ["5", "9", "8"], restaurantID: "1", prices: "$18", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "33", calories: "2", categoryID: "7", description: "Entree Ingredient Information", estimatedTime: "", images: [food2, "", ""], label: "", menuID: "3", name: "food33", order: "2", recommendedProducts: ["4", "5", "6"], restaurantID: "1", prices: "$19", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "34", calories: "2", categoryID: "7", description: "Entree Ingredient Information", estimatedTime: "", images: [food4, "", ""], label: "", menuID: "3", name: "food34", order: "3", recommendedProducts: ["5", "6", "8"], restaurantID: "1", prices: "$16", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "35", calories: "2", categoryID: "7", description: "Entree Ingredient Information", estimatedTime: "", images: [food2, "", ""], label: "", menuID: "3", name: "food35", order: "4", recommendedProducts: ["4", "3", "9"], restaurantID: "1", prices: "$12", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "36", calories: "2", categoryID: "8", description: "Entree Ingredient Information", estimatedTime: "", images: [food5, "", ""], label: "", menuID: "3", name: "food36", order: "0", recommendedProducts: ["4", "3", "9"], restaurantID: "1", prices: "$15", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "37", calories: "2", categoryID: "8", description: "Entree Ingredient Information", estimatedTime: "", images: [food3, "", ""], label: "", menuID: "3", name: "food37", order: "1", recommendedProducts: ["4", "3", "9"], restaurantID: "1", prices: "$14", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "38", calories: "2", categoryID: "8", description: "Entree Ingredient Information", estimatedTime: "", images: [food5, "", ""], label: "", menuID: "3", name: "food38", order: "2", recommendedProducts: ["4", "3", "9"], restaurantID: "1", prices: "$16", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "39", calories: "2", categoryID: "8", description: "Entree Ingredient Information", estimatedTime: "", images: [food1, "", ""], label: "", menuID: "3", name: "food39", order: "3", recommendedProducts: ["4", "3", "9"], restaurantID: "1", prices: "$21", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "40", calories: "2", categoryID: "8", description: "Entree Ingredient Information", estimatedTime: "", images: [food3, "", ""], label: "", menuID: "3", name: "food40", order: "4", recommendedProducts: ["4", "3", "9"], restaurantID: "1", prices: "$34", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "41", calories: "2", categoryID: "9", description: "Entree Ingredient Information", estimatedTime: "", images: [food2, "", ""], label: "", menuID: "3", name: "food41", order: "0", recommendedProducts: ["4", "3", "9"], restaurantID: "1", prices: "$15", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "42", calories: "2", categoryID: "9", description: "Entree Ingredient Information", estimatedTime: "", images: [food4, "", ""], label: "", menuID: "3", name: "food42", order: "1", recommendedProducts: ["4", "3", "9"], restaurantID: "1", prices: "$14", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "43", calories: "2", categoryID: "9", description: "Entree Ingredient Information", estimatedTime: "", images: [food2, "", ""], label: "", menuID: "3", name: "food43", order: "2", recommendedProducts: ["4", "3", "9"], restaurantID: "1", prices: "$16", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "44", calories: "2", categoryID: "9", description: "Entree Ingredient Information", estimatedTime: "", images: [food1, "", ""], label: "", menuID: "3", name: "food44", order: "3", recommendedProducts: ["4", "3", "9"], restaurantID: "1", prices: "$15", itemSize: "3", videos: ["", "", ""], views: "0" },
    { foodID: "45", calories: "2", categoryID: "9", description: "Entree Ingredient Information", estimatedTime: "", images: [food4, "", ""], label: "", menuID: "3", name: "food45", order: "4", recommendedProducts: ["4", "3", "9"], restaurantID: "1", prices: "$18", itemSize: "3", videos: ["", "", ""], views: "0" }
]